[package]
name = "regex-pool"
version = "0.1.1"
description = "Thread-safe reusable object pooling extracted from regex-automata."
license = "MIT OR Apache-2.0"
repository = "https://github.com/fuchsnj/regex_pool"
edition = "2021"
rust-version = "1.65"

[lib]
bench = false

[features]
default = ["std"]
std = ["alloc"]
alloc = []
